# SwiftLint Configuration

# 활성화할 규칙
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 비활성화할 규칙
disabled_rules:
  - trailing_whitespace
  - todo

# 제외할 경로
excluded:
  - Pods
  - .build
  - Derived
  - .tuist-bin
  - .tuist-cache
  - Tuist/.build
  - "**/Derived"
  - "**/*.generated.swift"
  - "**/TuistBundle+*.swift"
  - "**/TuistAssets+*.swift"

# 분석할 파일
included:
  - SnapCroc

# 규칙별 설정
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

# 강제 언래핑 경고
force_unwrapping: warning
force_cast: warning
force_try: warning

# 파일 헤더
# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/ .*?\.swift
#                     \/\/ SnapCroc
#                     \/\/
#                     \/\/ Created by .*? on \d{4}\.\d{2}\.\d{2}\.
#                     \/\/

reporter: "xcode"
